server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.252.249:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: mch1021
  jpa: 
    database: MySQL
    show-sql: true
  redis:
   url: 123.207.252.249
  rabbitmq:
    addresses: 123.207.252.249